name: I18n Keys Validate

on:
  push:
    paths:
      - i18n/*.json
  workflow_dispatch:

jobs:
  i18nkvali:
    name: I18n Keys Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: nanasess/setup-php@v4
        with:
          php-version: 8.3

      - name: Execute Test
        run: php maintenance/doI18nKeysCheck.php >> $GITHUB_STEP_SUMMARY
